### ISSUE TITLE
Add examples of shapes

### ISSUE THREAD

**Issue by DeflateAwning** [terrastruct/d2-playground#25]
In the **Syntax snippets** section of D2 Playground, I'd love to see examples of every shape that exists in the **Customize shape type** box:

```d2
diamond: { shape: diamond }
hexagon: { shape: hexagon}
...
```

**Comment by alixander** [comment]
the snippets are just meant to be previews, not references. d2lang.com will be the source for info like this

**Comment by DeflateAwning** [comment]
Where in the documentation is this exhaustive list?

**Comment by alixander** [comment]
@DeflateAwning https://d2lang.com/tour/shapes/#example
