### ISSUE TITLE
Variable example broken

### ISSUE THREAD

**Issue by n1ght-hunter** [terrastruct/d2-playground#43]
![image](https://github.com/terrastruct/d2/assets/66358962/c66b3e8b-7b12-404d-b9df-a6472a28d312)

should be 
`colors.primary`

**Comment by alixander** [comment]
https://github.com/terrastruct/d2-playground/pull/40

**Comment by NdagiStanley** [comment]
This is still broken on the site: https://play.d2lang.com/

<img width="1691" height="1094" alt="Variables snippet" src="https://github.com/user-attachments/assets/667d1769-841d-4f24-bc80-1e9bae903d21" />
