### ISSUE TITLE
Old play.d2lang.com URLs broke after d2/urlenc changes

### ISSUE THREAD

**Issue by jrcd-HR** [terrastruct/d2-playground#45]
Hello, I've been using play.d2lang.com to make diagrams and store them in a wiki page over the last few weeks. Pretty nice, thanks! I noticed this week that the URLs I had stored were broken. When I clicked them my elaborate diagrams started to only show a dreaded:

> x -> y

I decided to figure out why and I found that the URL encoded changed in the d2 repository, in a commit from Nov 7: https://github.com/terrastruct/d2/commit/5eead31c91fcc1f6c0ecaf28e3006758055efd8b

This did not take effect on the d2 playground site until d2 was upgraded for the deployed wasm, on Dec 6: https://github.com/terrastruct/d2-playground/commit/ae1e9c3bcd9896a978f80a0d1d370fea302e85a0

When the bundled, WASM version of d2 was deployed this created a cutoff date. Any URLs generated before the cutoff would no longer properly decode their embedded d2 "scripts". Only URLs for documents created after the cutoff date would decode properly.

The following is a Go program I used to convert old URLs to the new URLs. I read the above commit and decoded using the old deflate dictionary, then encoding with the same parameters as the new `urlenc.Encode`. I just wanted to share that with anyone who needs it.

https://gist.github.com/jrcd-HR/92ef3407c9f5061787b7c7a095a031ea

I'm not sure how to fix it, other than first trying the new `url.Decode` method, and then trying the backup method if that fails. Of course, the problem is that the backup method is no longer implemented in the d2 wasm.

**Comment by alixander** [comment]
Hi, indeed we have a notice on D2 about this in the latest release: https://github.com/terrastruct/d2/releases/tag/v0.6.2

It's the last encoding change that'll happen. Thank you for sharing that gist for folks.

By the way it's not documented right now but you can also render directly in your wiki: https://api.d2lang.com/render/svg?script=qlDQtVOo5AIEAAD__w%3D%3D&
