### ISSUE TITLE
Compile on ctrl-enter

### ISSUE THREAD

**Issue by JoshWillik** [terrastruct/d2-playground#61]
Hi,

As a totally new user, it was my first instinct press ctrl-enter evaluate my changes in the playground preview window.
It wasn't until I checked the code that I saw it was ctrl-s instead.

Would you accept a PR that makes ctrl-enter compile the diagram in addition to ctrl-s?

**Comment by alixander** [comment]
Sure, yes.

**Comment by JoshWillik** [comment]
Thank you!
